name: Premier Workflow

on: [push]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    
    steps:
      - name: Etape 1
        run: echo "Bonjour classe ICT324 !"
      
      - name: Etape 2
        run: echo "Ceci est mon premier workflow automatisé"
      
      - name: Etape 3
        run: echo "Fin du workflow"